// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Q1Entity;

namespace Q1Entity.Migrations
{
    [DbContext(typeof(DirectoryContext))]
    [Migration("20200912065008_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Q1Entity.DirectoryItem", b =>
                {
                    b.Property<int>("DirectoryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("DirectoryItemId");

                    b.ToTable("DirectoryItems");
                });

            modelBuilder.Entity("Q1Entity.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Q1Entity.UserDirectoryItem", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DirectoryItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "DirectoryItemId");

                    b.HasIndex("DirectoryItemId");

                    b.ToTable("UserDirectoryItems");
                });

            modelBuilder.Entity("Q1Entity.UserDirectoryItem", b =>
                {
                    b.HasOne("Q1Entity.DirectoryItem", "DirectoryItem")
                        .WithMany("UserDirectoryItems")
                        .HasForeignKey("DirectoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Q1Entity.User", "User")
                        .WithMany("UserDirectoryItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
